import type { ReuseBoxItem } from "@/components/reusebox/types";

const sampleAudio = "/assets/images/1.mp3";
const testPdf = "/assets/images/test.pdf";
const sampleYoutube =
  "https://www.youtube.com/watch?v=3IxoiPGWv_4&list=PLtbhZUljUX9W4Jb5YQrWO36UMmD_HzxFG";

export const scholarlyItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "audio",
    subtitle: "الشريط الأول",
    title: "شرح كتاب المختصر في صفات النبي ﷺ وأخلاقه",
    subtitleHref: "/ar/scholarly/1",
    titleHref: "/ar/scholarly/1",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 2,
    type: "audio",
    subtitle: "الشريط الثاني",
    title: "شرح كتاب التوحيد للإمام محمد بن عبد الوهاب",
    subtitleHref: "/ar/scholarly/1",
    titleHref: "/ar/scholarly/1",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 3,
    type: "video",
    subtitle: "الشريط الثالث",
    title: "شرح صحيح البخاري - كتاب الإيمان",
    subtitleHref: "/ar/scholarly/3",
    titleHref: "/ar/scholarly/3",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 4,
    type: "audio",
    subtitle: "الشريط الرابع",
    title: "شرح الأصول الثلاثة",
    subtitleHref: "/ar/scholarly/4",
    titleHref: "/ar/scholarly/4",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "الشريط الخامس",
    title: "شرح كشف الشبهات",
    subtitleHref: "/ar/scholarly/5",
    titleHref: "/ar/scholarly/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "video",
    subtitle: "الشريط السادس",
    title: "شرح العقيدة الواسطية",
    subtitleHref: "/ar/scholarly/6",
    titleHref: "/ar/scholarly/6",
    youtubeUrl: sampleYoutube,
  },
];

export const lectureItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "video",
    subtitle: "محاضرة ١",
    title: "أداب طالب العلم",
    subtitleHref: "/ar/lectures/1",
    titleHref: "/ar/lectures/1",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 2,
    type: "audio",
    subtitle: "محاضرة ٢",
    title: "أهمية التوحيد في حياة المسلم",
    subtitleHref: "/ar/lectures/2",
    titleHref: "/ar/lectures/2",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 3,
    type: "pdf",
    subtitle: "محاضرة ٣",
    title: "منهج السلف في فهم النصوص",
    subtitleHref: "/ar/lectures/3",
    titleHref: "/ar/lectures/3",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 4,
    type: "video",
    subtitle: "محاضرة ٤",
    title: "البر بالوالدين وصلة الرحم",
    subtitleHref: "/ar/lectures/4",
    titleHref: "/ar/lectures/4",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 5,
    type: "audio",
    subtitle: "محاضرة ٥",
    title: "الأخلاق الفاضلة في الإسلام",
    subtitleHref: "/ar/lectures/5",
    titleHref: "/ar/lectures/5",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 6,
    type: "pdf",
    subtitle: "محاضرة ٦",
    title: "أسباب الثبات على الدين",
    subtitleHref: "/ar/lectures/6",
    titleHref: "/ar/lectures/6",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
];

export const sermonItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "audio",
    subtitle: "خطبة الجمعة ١",
    title: "التقوى وأثرها في حياة المسلم",
    subtitleHref: "/ar/sermons/1",
    titleHref: "/ar/sermons/1",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 2,
    type: "pdf",
    subtitle: "خطبة الجمعة ٢",
    title: "أحوال القلوب وأمراضها",
    subtitleHref: "/ar/sermons/2",
    titleHref: "/ar/sermons/2",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 3,
    type: "video",
    subtitle: "خطبة الجمعة ٣",
    title: "خطورة المعاصي وعقوبة الذنوب",
    subtitleHref: "/ar/sermons/3",
    titleHref: "/ar/sermons/3",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 4,
    type: "audio",
    subtitle: "خطبة الجمعة ٤",
    title: "فضل رمضان وواجبات المؤمن فيه",
    subtitleHref: "/ar/sermons/4",
    titleHref: "/ar/sermons/4",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "خطبة الجمعة ٥",
    title: "حقوق الجار في الشريعة الإسلامية",
    subtitleHref: "/ar/sermons/5",
    titleHref: "/ar/sermons/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "video",
    subtitle: "خطبة الجمعة ٦",
    title: "الزكاة وأثرها في التكافل الاجتماعي",
    subtitleHref: "/ar/sermons/6",
    titleHref: "/ar/sermons/6",
    youtubeUrl: sampleYoutube,
  },
];

export const fatwaItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "audio",
    subtitle: "فتوى ١",
    title: "حكم صلاة الجماعة في المسجد",
    subtitleHref: "/ar/fatwas/1",
    titleHref: "/ar/fatwas/1",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 2,
    type: "pdf",
    subtitle: "فتوى ٢",
    title: "أحكام الطهارة والوضوء",
    subtitleHref: "/ar/fatwas/2",
    titleHref: "/ar/fatwas/2",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 3,
    type: "video",
    subtitle: "فتوى ٣",
    title: "حكم التعامل مع البنوك الربوية",
    subtitleHref: "/ar/fatwas/3",
    titleHref: "/ar/fatwas/3",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 4,
    type: "audio",
    subtitle: "فتوى ٤",
    title: "صيام المريض والمسافر",
    subtitleHref: "/ar/fatwas/4",
    titleHref: "/ar/fatwas/4",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "فتوى ٥",
    title: "أحكام الحج والعمرة للمبتدئين",
    subtitleHref: "/ar/fatwas/5",
    titleHref: "/ar/fatwas/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "video",
    subtitle: "فتوى ٦",
    title: "حكم التصوير والتصوير الفوتوغرافي",
    subtitleHref: "/ar/fatwas/6",
    titleHref: "/ar/fatwas/6",
    youtubeUrl: sampleYoutube,
  },
];

export const articleItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "pdf",
    subtitle: "مقالة ١",
    title: "أسس العقيدة الصحيحة عند أهل السنة",
    subtitleHref: "/ar/articles/1",
    titleHref: "/ar/articles/1",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 2,
    type: "pdf",
    subtitle: "مقالة ٢",
    title: "منهج أهل الحديث في النقد والجرح",
    subtitleHref: "/ar/articles/2",
    titleHref: "/ar/articles/2",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 3,
    type: "pdf",
    subtitle: "مقالة ٣",
    title: "التصفية والتربية في الدعوة إلى الله",
    subtitleHref: "/ar/articles/3",
    titleHref: "/ar/articles/3",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 4,
    type: "pdf",
    subtitle: "مقالة ٤",
    title: "التحذير من البدع والمحدثات",
    subtitleHref: "/ar/articles/4",
    titleHref: "/ar/articles/4",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "مقالة ٥",
    title: "فضل العلم وطلبه",
    subtitleHref: "/ar/articles/5",
    titleHref: "/ar/articles/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "pdf",
    subtitle: "مقالة ٦",
    title: "الوسطية في الإسلام مفهومًا وتطبيقًا",
    subtitleHref: "/ar/articles/6",
    titleHref: "/ar/articles/6",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
];

export const bookItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "pdf",
    subtitle: "كتاب ١",
    title: "المختصر في صفات النبي ﷺ وأخلاقه",
    subtitleHref: "/ar/books/1",
    titleHref: "/ar/books/1",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 2,
    type: "pdf",
    subtitle: "رسالة ١",
    title: "رسالة في التوحيد",
    subtitleHref: "/ar/books/2",
    titleHref: "/ar/books/2",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 3,
    type: "pdf",
    subtitle: "كتاب ٢",
    title: "أصول السنة",
    subtitleHref: "/ar/books/3",
    titleHref: "/ar/books/3",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 4,
    type: "pdf",
    subtitle: "رسالة ٢",
    title: "رسالة في آداب العلم",
    subtitleHref: "/ar/books/4",
    titleHref: "/ar/books/4",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "كتاب ٣",
    title: "معالم في طريق طلب العلم",
    subtitleHref: "/ar/books/5",
    titleHref: "/ar/books/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "pdf",
    subtitle: "رسالة ٣",
    title: "تنبيهات في منهج الدعوة",
    subtitleHref: "/ar/books/6",
    titleHref: "/ar/books/6",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
];

export const mostWatchedAudioVisualItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "audio",
    subtitle: "الأكثر استماعًا ١",
    title: "شرح كتاب المختصر في صفات النبي ﷺ وأخلاقه",
    subtitleHref: "/ar/most-watched/audio/1",
    titleHref: "/ar/most-watched/audio/1",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 2,
    type: "video",
    subtitle: "الأكثر مشاهدة ١",
    title: "أداب طالب العلم وكيفية الطلب",
    subtitleHref: "/ar/most-watched/video/1",
    titleHref: "/ar/most-watched/video/1",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 3,
    type: "audio",
    subtitle: "الأكثر استماعًا ٢",
    title: "التقوى وأثرها في حياة المسلم",
    subtitleHref: "/ar/most-watched/audio/2",
    titleHref: "/ar/most-watched/audio/2",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 4,
    type: "video",
    subtitle: "الأكثر مشاهدة ٢",
    title: "أهمية التوحيد في حياة المسلم",
    subtitleHref: "/ar/most-watched/video/2",
    titleHref: "/ar/most-watched/video/2",
    youtubeUrl: sampleYoutube,
  },
  {
    id: 5,
    type: "audio",
    subtitle: "الأكثر استماعًا ٣",
    title: "فضل رمضان وواجبات المؤمن فيه",
    subtitleHref: "/ar/most-watched/audio/3",
    titleHref: "/ar/most-watched/audio/3",
    audioUrl: sampleAudio,
    downloadUrl: sampleAudio,
    progress: 0,
  },
  {
    id: 6,
    type: "video",
    subtitle: "الأكثر مشاهدة ٣",
    title: "شرح العقيدة الواسطية - المجلس الأول",
    subtitleHref: "/ar/most-watched/video/3",
    titleHref: "/ar/most-watched/video/3",
    youtubeUrl: sampleYoutube,
  },
];

export const mostWatchedReadingItems: ReuseBoxItem[] = [
  {
    id: 1,
    type: "pdf",
    subtitle: "الأكثر قراءة ١",
    title: "أسس العقيدة الصحيحة عند أهل السنة",
    subtitleHref: "/ar/most-watched/reading/1",
    titleHref: "/ar/most-watched/reading/1",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 2,
    type: "pdf",
    subtitle: "الأكثر قراءة ٢",
    title: "المختصر في صفات النبي ﷺ وأخلاقه",
    subtitleHref: "/ar/most-watched/reading/2",
    titleHref: "/ar/most-watched/reading/2",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 3,
    type: "pdf",
    subtitle: "الأكثر قراءة ٣",
    title: "رسالة في التوحيد",
    subtitleHref: "/ar/most-watched/reading/3",
    titleHref: "/ar/most-watched/reading/3",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 4,
    type: "pdf",
    subtitle: "الأكثر قراءة ٤",
    title: "التحذير من البدع والمحدثات",
    subtitleHref: "/ar/most-watched/reading/4",
    titleHref: "/ar/most-watched/reading/4",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 5,
    type: "pdf",
    subtitle: "الأكثر قراءة ٥",
    title: "فضل العلم وطلبه",
    subtitleHref: "/ar/most-watched/reading/5",
    titleHref: "/ar/most-watched/reading/5",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
  {
    id: 6,
    type: "pdf",
    subtitle: "الأكثر قراءة ٦",
    title: "معالم في طريق طلب العلم",
    subtitleHref: "/ar/most-watched/reading/6",
    titleHref: "/ar/most-watched/reading/6",
    downloadUrl: testPdf,
    viewUrl: testPdf,
  },
];
